---
Resources:
  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      AvaliabilityZone: ap-southeast-1b
      InstanceType: t2.micro
      ImageId: ami-08be951cec06726be
      KeyName: zabbixkp
      SecurityGroup: cloudformationsg

  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: ap-southeast-1b
      ImageId: ami-08be951cec06726be
      KeyName: zabbixkp
      SecurityGroup: cloudformationsg

  cloudformationsg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH Service
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
