---
Resources:
  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      AvaliabilityZone: us-east-1a
      InstanceType: t2.micro
      ImageId: ami-0c55b159cbfafe1f0
      KeyName: myKeyPair

  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c55b159cbfafe1f0
      KeyName: myKeyPair